# Generated by rust2rpm 13
%bcond_without check
%global debug_package %{nil}

%global crate mailparse

Name:           rust-%{crate}
Version:        0.10.4
Release:        1%{?dist}
Summary:        Simple parser for MIME e-mail messages

# Upstream license specification: 0BSD
License:        0BSD
URL:            https://crates.io/crates/mailparse
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Simple parser for MIME e-mail messages.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon Feb 10 2020 Josh Stone <jistone@redhat.com> - 0.10.4-1
- Update to 0.10.4

* Mon Feb 03 15:52:06 EET 2020 Artem Polishchuk <ego.cordatus@gmail.com> - 0.10.3-1
- Update to 0.10.3

* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.10.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Tue Jan 07 2020 Josh Stone <jistone@redhat.com> - 0.10.2-1
- Update to 0.10.2

* Tue Dec 10 2019 Artem Polishchuk <ego.cordatus@gmail.com> - 0.10.1-1
- Update to 0.10.1

* Wed Nov 27 15:40:25 CET 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.2-1
- Initial package
